version: '3.8'
services:
  socialnetwork-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 8080:80
    container_name: socialNetwork-frontend
    stdin_open: true
    volumes:
       - /app/node_modules
    depends_on:
      - socialnetwork-backend
    restart: unless-stopped
    networks:
      - socialNetwork
      - nginx-manager_default
    
  db:
    image: mariadb
    container_name: socialNetwork-mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: random
      MARIADB_DATABASE: socialNetwork
      MARIADB_USER: strapi
      MARIADB_PASSWORD: strapi
    ports:
      - 3306:3306
    volumes: 
      - socialNetwork-mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
    - socialNetwork

  socialnetwork-backend:
    # image: strapi/strapi
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: socialNetwork-backend
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: socialNetwork
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    ports:
      - '1337:1337'
    volumes:
      - ./backend/config:/opt/app/config
      - ./backend/src:/opt/app/src
      - ./backend/package.json:/opt/package.json
      - ./backend/.env:/opt/app/.env
      - ./backend/yarn.lock:/opt/yarn.lock
      - ./backend/public/uploads:/opt/app/public/uploads
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - socialNetwork
      - nginx-manager_default

networks:
  socialNetwork:
  nginx-manager_default:
    external: true
volumes:
  socialNetwork-mariadb: